site_name: automl-demo
repo_url: https://github.com/danielpgp1012/automl-demo
site_url: https://danielpgp1012.github.io/automl-demo
site_description: Create and serve small models
site_author: Daniel Pacheco
edit_uri: edit/main/docs/
repo_name: danielpgp1012/automl-demo
copyright: Maintained by <a href="https://danielpgp1012.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/danielpgp1012/automl-demo
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/automl-demo

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
